platform :ios, '6.0'
inhibit_all_warnings!

pod 'Parse', '~> 1.2.5'
pod 'TestFlightSDK', '~> 1.3.0-beta.6'
pod 'HCYoutubeParser', '~> 0.0.1'
pod 'XCDYouTubeVideoPlayerViewController', '~> 1.0.0'
pod 'HMSegmentedControl', '~> 1.2.0'
pod 'REMenu', '~> 1.3.1'
pod 'MLPAutoCompleteTextField', '~> 1.3'
pod 'MYIntroduction', :git => 'git@github.com:jstart/MYIntroductionView.git'
pod 'Facebook-iOS-SDK', '~> 3.2.1'
pod 'ALActionBlocks', '~> 1.0'
pod 'DCIntrospect', '~> 0.0.2'
pod 'SSToolkit', '~> 1.0.3'
pod 'UIColor-Utilities', '~> 1.0.1'
pod 'UIResponder+KeyboardCache', '~> 0.1'
pod 'XCDFormInputAccessoryView', '~> 1.0.0'
pod 'SVPullToRefresh'
# pod 'Foursquare-API-v2', :podspec => "Local Podspecs/Foursquare-API-V2.podspec"
pod 'UISS', '~> 1.1.0'
pod 'StyledTableViewCell-for-iOS', '~> 1.0'
pod 'RCLocationManager', '~> 0.1'
pod 'PonyDebugger', '~> 0.3.0'
pod 'ZBarSDK', '~> 1.3.1'
pod 'MBAlertView', '~> 1.0.0'
pod 'FlatUIKit', '~> 1.1'
pod 'MTStatusBarOverlay', '~> 0.9.1'
pod 'QBFlatButton', '~> 1.0'

