platform :ios, '5.0'
pod 'Parse', '~> 1.2.5'
pod 'HCYoutubeParser', '~> 0.0.1'
pod 'HMSegmentedControl', '~> 1.2.0'
pod 'REMenu', '~> 1.3.1'
pod 'MLPAutoCompleteTextField', '~> 1.1'
pod 'MYIntroduction', :git => 'https://github.com/jstart/iPhone-IntroductionTutorial.git'
pod 'Facebook-iOS-SDK', '~> 3.2.1'
pod 'ALActionBlocks', '~> 1.0'
pod 'DCIntrospect', '~> 0.0.2'
pod 'SSToolkit', '~> 1.0.3'
pod 'UIColor-Utilities', '~> 1.0.1'
pod 'UIResponder+KeyboardCache', '~> 0.1'
pod 'XCDFormInputAccessoryView', '~> 1.0.0'
pod 'SVPullToRefresh'


